# -*- coding: utf-8 -*-
"""WineDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bq7bzxL9R0seq59UgKh02p5Y1hiRGqe
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model,metrics

diabetic= datasets.load_wine()
diabetic

diabetic.feature_names

diabetic.data

data=pd.DataFrame(diabetic.data,columns=diabetic.feature_names)
y=diabetic.target

diabetic.feature_names

data.shape

data.head()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
model=LogisticRegression()

X_train,X_test,y_train,y_test=train_test_split(data,y,test_size=0.2,random_state=10)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

import pickle
Pkl_Filename="Lr_pickle.pkl"
with open(Pkl_Filename,'wb') as file:
  pickle.dump(model,file)

with open(Pkl_Filename,'rb') as file:
  Pickled_LR_Model=pickle.load(file)

Pickled_LR_Model.predict(X_test)